name: MANUAL - Destroy Infrastructure via Terraform

on:
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure deletion.'
        required: true
        default: 'do-not-destroy'
      environment_config:
        description: 'Environment to destroy (e.g., dev, staging). This dictates which tfvars to use for context.'
        required: true
        default: 'dev'

env:
  AWS_REGION: ap-south-1 # Or from tfvars if it changes per environment
  # TF_VAR_... for any sensitive variables needed for destroy (usually not many)

jobs:
  terraform-destroy:
    if: github.event.inputs.confirm_destroy == 'destroy'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # If using OIDC for Terraform

    # Define an environment for potential manual approval step
    environment:
      name: destroy-approval # Create this environment in repo Settings > Environments
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} # Optional: Link to workflow run

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: main-infra

    - name: Checkout TFVars from Config Repo
      uses: actions/checkout@v4
      with:
        repository: VedantDomadiya/hello-world-infra-configs 
        token: ${{ secrets.CONFIG_REPO_PAT }}
        path: config-repo
        ref: main # Or your config branch

    # Configure AWS Credentials (using OIDC or secrets)
    # Ensure these credentials have Terraform permissions to destroy resources
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Determine TFVars Path
      id: tfvars_path
      run: echo "path=./config-repo/terraform.tfvars" >> $GITHUB_OUTPUT

    - name: Verify TFVars File
      run: |
        echo "Looking for tfvars file at: ${{ steps.tfvars_path.outputs.path }}"
        ls -la ./config-repo/
        if [ ! -f "${{ steps.tfvars_path.outputs.path }}" ]; then
          echo "Error: ${{ steps.tfvars_path.outputs.path }} not found!"
          exit 1
        fi
        echo "TFVars file found."

    - name: Terraform Init
      id: init
      run: terraform -chdir=./terraform init # Must initialize with same backend config

    - name: Terraform Plan Destroy
      id: plan-destroy
      run: |
        echo "--- Planning destruction ---"
        terraform -chdir=./terraform plan -destroy -no-color -input=false
        # This step shows what *would* be destroyed. It doesn't destroy yet.

    # --- Optional: Manual Approval Gate ---
    # This step relies on the 'destroy-approval' environment configured in your
    # repository settings (Settings > Environments). Add a "Required reviewers"
    # protection rule to this environment to enforce manual approval before proceeding.
    # If you don't configure the environment protection rule, this step does nothing extra.
    - name: Waiting for approval to destroy... (Check Environment Protection Rules)
      run: echo "Proceeding to destroy after manual approval (if configured)."

    - name: Terraform Destroy
      id: destroy
      run: |
        echo "--- Applying destruction ---"
        terraform -chdir=./terraform destroy -auto-approve -input=false

    - name: Destruction Complete
      run: echo "Infrastructure destruction process finished."

  cancel-if-not-confirmed:
    if: github.event.inputs.confirm_destroy != 'destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: |
          echo "Destruction not confirmed. Input was '${{ github.event.inputs.confirm_destroy }}', expected 'destroy'."
          # Optionally fail the workflow explicitly
          exit 1